# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dish_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 253)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label.setObjectName("label")
        self.inputName = QtWidgets.QLineEdit(self.centralwidget)
        self.inputName.setGeometry(QtCore.QRect(10, 80, 331, 20))
        self.inputName.setObjectName("inputName")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 51, 16))
        self.label_2.setObjectName("label_2")
        self.chooseCategory = QtWidgets.QComboBox(self.centralwidget)
        self.chooseCategory.setGeometry(QtCore.QRect(10, 30, 331, 22))
        self.chooseCategory.setObjectName("chooseCategory")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 161, 16))
        self.label_3.setObjectName("label_3")
        self.inputAddInfo = QtWidgets.QLineEdit(self.centralwidget)
        self.inputAddInfo.setGeometry(QtCore.QRect(10, 130, 331, 20))
        self.inputAddInfo.setObjectName("inputAddInfo")
        self.checkIsSale = QtWidgets.QCheckBox(self.centralwidget)
        self.checkIsSale.setGeometry(QtCore.QRect(10, 160, 81, 17))
        self.checkIsSale.setObjectName("checkIsSale")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(250, 180, 91, 23))
        self.saveButton.setObjectName("saveButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Категория"))
        self.label_2.setText(_translate("MainWindow", "Название"))
        self.label_3.setText(_translate("MainWindow", "Дополнительная информация"))
        self.checkIsSale.setText(_translate("MainWindow", "В продаже"))
        self.saveButton.setText(_translate("MainWindow", "Сохранить"))
