# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'order_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label.setObjectName("label")
        self.outputAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.outputAddress.setGeometry(QtCore.QRect(10, 30, 331, 20))
        self.outputAddress.setObjectName("outputAddress")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.label_2.setObjectName("label_2")
        self.outputInfo = QtWidgets.QLineEdit(self.centralwidget)
        self.outputInfo.setGeometry(QtCore.QRect(10, 80, 331, 20))
        self.outputInfo.setObjectName("outputInfo")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 47, 13))
        self.label_3.setObjectName("label_3")
        self.outputSum = QtWidgets.QLineEdit(self.centralwidget)
        self.outputSum.setGeometry(QtCore.QRect(10, 130, 331, 20))
        self.outputSum.setObjectName("outputSum")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 71, 16))
        self.label_4.setObjectName("label_4")
        self.outputTime = QtWidgets.QLineEdit(self.centralwidget)
        self.outputTime.setGeometry(QtCore.QRect(10, 180, 331, 20))
        self.outputTime.setObjectName("outputTime")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 210, 47, 13))
        self.label_5.setObjectName("label_5")
        self.orderList = QtWidgets.QListWidget(self.centralwidget)
        self.orderList.setGeometry(QtCore.QRect(10, 230, 331, 192))
        self.orderList.setObjectName("orderList")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 440, 91, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Адрес"))
        self.label_2.setText(_translate("MainWindow", "Другая информация"))
        self.label_3.setText(_translate("MainWindow", "Сумма"))
        self.label_4.setText(_translate("MainWindow", "Время заказа"))
        self.label_5.setText(_translate("MainWindow", "Заказ"))
        self.pushButton.setText(_translate("MainWindow", "Выполнено"))
