# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'version_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 283)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label.setObjectName("label")
        self.chooseCategory = QtWidgets.QComboBox(self.centralwidget)
        self.chooseCategory.setGeometry(QtCore.QRect(10, 30, 331, 22))
        self.chooseCategory.setObjectName("chooseCategory")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 47, 13))
        self.label_2.setObjectName("label_2")
        self.chooseDish = QtWidgets.QComboBox(self.centralwidget)
        self.chooseDish.setGeometry(QtCore.QRect(10, 80, 331, 22))
        self.chooseDish.setObjectName("chooseDish")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 41, 16))
        self.label_3.setObjectName("label_3")
        self.inputSize = QtWidgets.QLineEdit(self.centralwidget)
        self.inputSize.setGeometry(QtCore.QRect(10, 130, 331, 20))
        self.inputSize.setObjectName("inputSize")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 47, 13))
        self.label_4.setObjectName("label_4")
        self.inputPrice = QtWidgets.QSpinBox(self.centralwidget)
        self.inputPrice.setGeometry(QtCore.QRect(10, 180, 331, 22))
        self.inputPrice.setObjectName("inputPrice")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(250, 210, 91, 23))
        self.saveButton.setObjectName("saveButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Категория"))
        self.label_2.setText(_translate("MainWindow", "Блюдо"))
        self.label_3.setText(_translate("MainWindow", "Размер"))
        self.label_4.setText(_translate("MainWindow", "Цена"))
        self.saveButton.setText(_translate("MainWindow", "Сохранить"))
